/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Samantha
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        saladtab = new javax.swing.JPanel();
        S1 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        S4 = new javax.swing.JLabel();
        rollstab = new javax.swing.JPanel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(153, 204, 255));
        head.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\logo.png")); // NOI18N
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 746, 62));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "QTY", "PRICE", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setGridColor(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 286, -1, 133));

        S1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_1.png")); // NOI18N
        S1.setText("jLabel1");

        S2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_2.png")); // NOI18N
        S2.setText("jLabel3");

        S3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_3.png")); // NOI18N
        S3.setText("jLabel2");

        S4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_4.png")); // NOI18N
        S4.setText("jLabel4");

        javax.swing.GroupLayout saladtabLayout = new javax.swing.GroupLayout(saladtab);
        saladtab.setLayout(saladtabLayout);
        saladtabLayout.setHorizontalGroup(
            saladtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saladtabLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(S1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(S2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(S3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(S4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        saladtabLayout.setVerticalGroup(
            saladtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saladtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saladtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S3)
                    .addComponent(S4)
                    .addComponent(S2)
                    .addComponent(S1))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("SALAD", saladtab);

        R1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_5.png")); // NOI18N
        R1.setText("jLabel5");

        R2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_6.png")); // NOI18N
        R2.setText("jLabel6");

        R3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_7.png")); // NOI18N
        R3.setText("jLabel7");

        R4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\food_8.png")); // NOI18N
        R4.setText("jLabel8");

        javax.swing.GroupLayout rollstabLayout = new javax.swing.GroupLayout(rollstab);
        rollstab.setLayout(rollstabLayout);
        rollstabLayout.setHorizontalGroup(
            rollstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rollstabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        rollstabLayout.setVerticalGroup(
            rollstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rollstabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rollstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R4)
                    .addComponent(R3)
                    .addComponent(R2)
                    .addComponent(R1))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("ROLLS", rollstab);

        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 68, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samantha\\Desktop\\netbeans project\\project3\\assets\\logout_icon.png")); // NOI18N
        jButton1.setText("LOGIN Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login log=new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel rollstab;
    private javax.swing.JPanel saladtab;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
